title: My Doggos
email: joey@apollorion.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my doggos
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
home_location: "Pickerington, Ohio 43147"

owners:
  - name: Joey Stout
    phone: "+1-614-999-4394"
    email: "joey@apollorion.com"
  - name: Kaylin Stout
    phone: "+1-614-905-1914"
    email: "kaylin@apollorion.com"

collections:
  doggos:
    output: true

defaults:
  - scope:
      path: ""
      type: "doggos"
    values:
      layout: "doggo"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"